# tasks file for install-commons
    - name: Check host connectivity
      ping:
    - name: Install commons
      yum:
        name: ["git", "firewalld"]
        state: present
        
    - name: Enable firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes