# tasks file for install-commons
    - name: Check host connectivity
      ping:
    - name: Install commons
      yum:
        name: "{{item}}"
        state: present
      with_items: 
          - git
          - firewalld