---
# tasks file for install-apache
    - name: Install apache and php
      ping:
    - name: Install commons
      yum:
        name: ["httpd", "php", "php-mysqlnd"]
        state: present
        
    - name: Set Apache firewall port
      firewalld:
        zone: public
        port: 80/tcp
        permanent: yes
        state: enabled
        
    - name: Reload firewalld
      systemd:
        name: firewalld
        state: reloaded