---
# tasks file for install-apache
    - name: Install apache and php
      yum:
        name: ["httpd", "php", "php-mysqlnd"]
        state: present
        
    - name: Set Apache firewall port
      firewalld:
        zone: public
        port: 80/tcp
        permanent: yes
        state: enabled
        
    - name: Reload firewalld
      systemd:
        name: firewalld
        state: reloaded
        
    - name: Replace index.html to index.php
      replace:
        path: /etc/httpd/conf/httpd.conf
        before: "DirectoryIndex index.html"
        after: "DirectoryIndex index.php"
        regexp: ".*DirectoryIndex index.html"