---
# tasks file for clone-and-configure-site
        
    - name: Clone a a Kodecloud project to destination
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html/
        
    - name: Replace db ip in index.php
      replace:
        path: /var/www/html/index.php
        replace: "localhost"
        regexp: ".*172.20.1.101"