---
# tasks file for install-mariadb

    - name: Install and configure MariaDB
      yum:
        name: ["mariadb-server", "python3-PyMySQL"]
        state: present
        
    - name: Create MariaDB config file
      file:
        path: /etc/my.cnf
        state: touch
        
    - name: Enable MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes
    
    - name: Set MariaDB firewall port
      firewalld:
        zone: public
        port: 3306/tcp
        permanent: yes
        state: enabled
        
    - name: Reload firewalld
      systemd:
        name: firewalld
        state: reloaded
        
    - name: create database
      community.mysql.mysql_db:
          name: ecomdb
          state: present
          register: database_creation_status
          
    - name: create db_user
      community.mysql.mysql_user:
          name: ecomdb
          password: ecompassword
          priv: "*.*:ALL"
          state: present
    
    - name: copy sql import file
      copy:
        src: "{{ role_path }}/files/db-load-script.sql"
        dest: /tmp/db-load-script.sql
      when: database_creation_status.changed
          
    - name: initialize database with sql-import
      community.mysql.mysql_db:
          name: ecomdb
          state: import
          target: /tmp/db-load-script.sql
      when: database_creation_status.changed
          