---
# tasks file for install-mariadb

    - name: Install and configure MariaDB
      yum:
        name: mariadb-server
        state: present
        
    - name: Create MariaDB config file
      file:
        path: /etc/my.cnf
        state: touch
        
    - name: Enable MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes
    
    - name: Set MariaDB firewall port
      ansible.posix.firewalld:
        zone: public
        port: 3306/tcp
        permanent: yes
        state: enabled
        
        
        